 - name: Devops
   hosts: [inha]
   become: yes

   tasks:         
       - name: Update servers
         apt:
           update_cache: yes
  
       - name: Install dependecis for Docker
         apt:
           name:
             - ca-certificates
             - curl
             - gnupg
             - lsb-release
           state: present

       - name: Add key to apt
         apt_key:
           url: https://download.docker.com/linux/ubuntu/gpg 
           state: present

       - name: Add specified repository into sourse list
         apt_repository:
           repo: deb https://download.docker.com/linux/ubuntu bionic stable
           state: present

       - name: Update servers
         apt:
           update_cache: yes

       - name: Install  Docker
         apt:
           name:
             - docker-ce
             - docker-ce-cli
             - containerd.io
           state: present

       - name: Install python3
         apt:
           name: python3.8
           state: latest

       - name: install python dependencies
         apt:
            name: python3-pip
            state: latest
 
       - name: Install docker pip
         pip:
            name: docker

       - name: Start Docker service
         service:
            name: docker
            state: started

#      - name: Create and start services
#        docker_compose:
#          project_src: /
#        register: output

       - name: Install Apache
         apt:
            name: apache2
            state: latest

       - name: Start Apache service
         service:
            name: apache2
            state: started

