name: 'Ansible'

on:

jobs:

   - id: host
     env:
          SSH: ${{ secrets.SSH_PRIVATE_KEY }}
     run: |
            host=$(grep "ec2_endpoint" terraform.log | awk -F  ":" '{print $1}' )
            host=${host//'ec2_endpoint = "'}
            host=${host//'"'}
            echo $host >> ansible/hosts
            echo "$SSH" > ansible/key.pem
            chmod 400 ansible/key.pem
            cat ansible/lesson9.pem

   - name: Ansible
     uses: saubermacherag/ansible-playbook-docker-action@v1.3
     with:
          playbookName: 'ansible/deploy.yml'
          inventoryFile: 'ansible/hosts'
          keyFile: 'ansible/lesson9.pem'
