name: 'Ansible'

on:
  push:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
            
    - name: Ansible
      uses: saubermacherag/ansible-playbook-docker-action@v1.3
      with:
          playbookName: 'ansible/deploy.yml'
          inventoryFile: 'ansible/hosts'
          keyFile: 'ansible/lesson9.pem'
