name: Docker Image CI

on:
  push:

jobs:

  build:


    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Dockerize
      if: success()
      uses: manusa/actions-publish-docker@v1.1.2
      with:
       name: inhamysnyk/github
       username: ${{ secrets.DOCKER_HUB_USER }}
       password: ${{ secrets.DOCKER_HUB_PASSWORD }}
       dockerfile path: ./app/Dockerfile

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
          context: ./
          file: ./app/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags:  ${{ secrets.DOCKER_HUB_USERNAME }}/simplewhale:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
    
    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
